### ISSUE TITLE
Tagging Support: IAM

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1129]
Add support for the creation of tags on the AWS Cloudformation resources

-  AWS::IAM::User
- AWS::IAM::Role

**Comment by ken9ross** [comment]
What name should be used for the tags (if any)?

If a name is supplied - use that
Otherwise, if an array of trusted services is supplied concatenate sorted list space delimited
Otherwise, if an array of federated services is supplied concatenate sorted list space delimited
Otherwise, none (don't see how this could happen, but a catchall)

Alternate would be the first value when multiple are supplied for trusted or federated services on the assumption that people would tend to list the most important first

Thoughts?

**Comment by roleyfoley** [comment]
I think we can just go with the name if its supplied. 
The others don't create anything unique per role trusted services is a fixed list of AWS service ids so won't create anything unique. Same goes for federated services.
