### ISSUE TITLE
Module Artefact Handling

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine#1453]
## Desired Behaviour

As a Hamlet user I would like to be able to develop `Modules` that make use of both common and bespoke deployment artefacts so that I may develop "out-of-the-box" modules that enable specific functionality that involve application-level components.

## Current Behaviour
There is currently nothing stopping `Modules` from making use of artefacts provided by users however there is no way for a build artefact to be bundled together with a `Module` that would require no additional effort from user. 

Currently if I wish to develop a module that makes use of a community-developed and publicly available docker image that is hosted in dockerhub, there is no way for me to reference the image and have it immediately available to my module. Instead, I must already have my account registries deployed and then manually pull/push the image into my registry in order for the module to make use of it. Whilst it is possible for this to be documented it is an additional overhead to module.

**Comment by roleyfoley** [comment]
I think this is probably not a specific thing to modules ( modules shouldn't implement new things ) and is more external artefact imports for components. Since the artefact type and its packaging is dependent on the type of component, i.e. docker images only work for ECS/Container* components and lambda zips only work in lamdba 

So essentially being able to define an external image as part of a components definition,  then as part of its deployment get the external artefact, save it to our local registry and then continue with the deployment referencing that image.

**Comment by RossMurr4y** [comment]
Would such functionality still extend to modules, if not exclusive to it? I can still see a lot of benefit for say a software vendor being able to have you implement their product in the cloud by only installing their module.

**Comment by roleyfoley** [comment]
@RossMurr4y how do you feel about the lambda implementation in #1456? Does this satisfy this requirement? 

if it does should we close this out and create tickets to implement this across components which have build artefacts?

**Comment by RossMurr4y** [comment]
Yep, will create a master ticket for this so we can discuss the scope of that.
