### ISSUE TITLE
Generation Contract to factor in Failed States

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine#1492]
## Expected Behaviour

When a Generation Contract is created and the Deployment Mode is `create` (not `update`), the current stack output has its `StackStatus` evaluated. If the status is of a state that has failed such as `ROLLBACK_COMPLETE` then a Contract Step should be added to delete the failed creation attempt prior to its new deploy step.

## Current Behaviour

If a stack deployment fails to create for any reason and a stack rollback occurs, the stack must first initially be deleted before the deployment can proceed. This becomes quite complicated when using `hamlet deploy run-deployments` because you may have a large number of resources that failed to create and now have to delete them yourself before a re-deployment can occur. 

## Context

save time spent on tracking down which deployment units failed to deploy in a large product by enabling the Contract to do this all on the users behalf

**Comment by RossMurr4y** [comment]
@hamlet-io/engine-maintainers is there sufficient separation of states between a `stack.json` for a failed-but-new template (safe for us to blat) and a failed-but-already-existed rollback (not safe to blat, the rollback goes back to a known working state) in order to accomplish this?

**Comment by roleyfoley** [comment]
I think that might be more of an executor thing rather than making it part of the contracts. The contracts outline what needs to be done, and deleting something that didn't work isn't really up to the contract to outline how to handle as that could mean different things at different times  

Maybe this is more of how the executor has handled the management contract. When deploying did it follow them in order and should it have given up on the first failure rather than continue since we need to handle the deployment order specifically.

**Comment by RossMurr4y** [comment]
Good point - I've raised a new ticket for this on the Executor instead.

Closing ticket in favour of Executor issue https://github.com/hamlet-io/executor-bash/issues/137
